version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "3004:3004"
    command: ["redis-server", "--port", "3004"]

  mongodb:
    image: mongo:7
    command: mongod --quiet --logpath /dev/null
    ports:
      - "3006:3006"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./openosint-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./openosint-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./openosint-backend
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./openosint-backend:/app
      - /app/node_modules
      - data-volume:/data
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis-worker:
    build: ./redis-worker
    depends_on:
      - redis
      - backend
    volumes:
      - data-volume:/data

  nginx:
    image: nginx:latest
    container_name: openosint-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend

volumes:
  mongo-data:
  data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/huber/openosint/shared-data