version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./openosint-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./openosint-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis

  redis-worker:
    build: ./redis-worker
    depends_on:
      - redis
      - backend

volumes:
  mongo-data: